### POST LIST
POST http://localhost:3000/lists
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTI1N2EzYzBjMmExZDhjM2ZjOTg0In0sImlhdCI6MTY5MDAwMjg5MH0.PZ6bV6Qy43nzeWGei5GSff_eFPUqEVe3ejsB9_UUiHM
Content-Type: application/json

{
    "name": "LIST 11 NEW EDITION"
}

### GET LISTS
GET http://localhost:3000/lists
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTI1N2EzYzBjMmExZDhjM2ZjOTg0In0sImlhdCI6MTY5MDAwMjg5MH0.PZ6bV6Qy43nzeWGei5GSff_eFPUqEVe3ejsB9_UUiHM

### GET LIST
GET http://localhost:3000/lists/64b8b76bde10440388854302
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTI1N2EzYzBjMmExZDhjM2ZjOTg0In0sImlhdCI6MTY5MDAwMjg5MH0.PZ6bV6Qy43nzeWGei5GSff_eFPUqEVe3ejsB9_UUiHM

### GET LIST
PATCH http://localhost:3000/lists/64b8b76bde10440388854302
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTI1N2EzYzBjMmExZDhjM2ZjOTg0In0sImlhdCI6MTY5MDAwMjg5MH0.PZ6bV6Qy43nzeWGei5GSff_eFPUqEVe3ejsB9_UUiHM
Content-Type: application/json

{
    "name": "LIST 1 (updated2)"
}

### DELETE TODO
DELETE http://localhost:3000/lists/64b8b76bde10440388854302
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTI1N2EzYzBjMmExZDhjM2ZjOTg0In0sImlhdCI6MTY5MDAwMjg5MH0.PZ6bV6Qy43nzeWGei5GSff_eFPUqEVe3ejsB9_UUiHM
