### POST LIST
POST http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTI1N2EzYzBjMmExZDhjM2ZjOTg0In0sImlhdCI6MTY5MDAwMjg5MH0.PZ6bV6Qy43nzeWGei5GSff_eFPUqEVe3ejsB9_UUiHM
Content-Type: application/json

{
    "name": "todooof",
    "description": "toddoooo 3"
}

### Show todo
GET  http://localhost:3000/todos/64bb643ae68844bb3fa6f162
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTI1N2EzYzBjMmExZDhjM2ZjOTg0In0sImlhdCI6MTY5MDAwMjg5MH0.PZ6bV6Qy43nzeWGei5GSff_eFPUqEVe3ejsB9_UUiHM


### get todos
GET  http://localhost:3000/todos/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTI1N2EzYzBjMmExZDhjM2ZjOTg0In0sImlhdCI6MTY5MDAwMjg5MH0.PZ6bV6Qy43nzeWGei5GSff_eFPUqEVe3ejsB9_UUiHM

### edit todo
PATCH  http://localhost:3000/todos/64bb5022a136ee547e7cd248
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTI1N2EzYzBjMmExZDhjM2ZjOTg0In0sImlhdCI6MTY5MDAwMjg5MH0.PZ6bV6Qy43nzeWGei5GSff_eFPUqEVe3ejsB9_UUiHM
Content-Type: application/json

{
    "name": "todooo",
    "description": "tod"
}

### delete todo
DELETE   http://localhost:3000/todos/64bb5022a136ee547e7cd248
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTI1N2EzYzBjMmExZDhjM2ZjOTg0In0sImlhdCI6MTY5MDAwMjg5MH0.PZ6bV6Qy43nzeWGei5GSff_eFPUqEVe3ejsB9_UUiHM